# This workflow generates an SLSA provenance file for your project.
# It satisfies level 3 for provenance requirements as outlined by the SLSA specifications.
# The project is an initiative of the OpenSSF (openssf.org) and is developed at
# https://github.com/slsa-framework/slsa-github-generator.
# For more information on SLSA and how it enhances software supply chain security, visit slsa.dev.

name: SLSA Provenance Generator

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.digests }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ========================================================
      #
      # Step 1: Build your artifacts.
      #
      # Customize this step to match your project's build commands.
      #
      # ========================================================
      - name: Build Artifacts
        run: |
          # Replace the following lines with actual build commands
          echo "Building artifacts..."
          echo "artifact1" > artifact1
          echo "artifact2" > artifact2
          echo "Build complete."

      # ========================================================
      #
      # Step 2: Generate provenance subjects.
      # Update the sha256 sum arguments to include all artifacts.
      #
      # ========================================================
      - name: Generate Subject for Provenance
        id: hash
        run: |
          set -euo pipefail

          # List the artifacts the provenance will refer to.
          files=$(ls artifact*)
          if [ -z "$files" ]; then
            echo "No artifacts found!"
            exit 1
          fi

          # Generate the subjects (base64 encoded).
          echo "hashes=$(sha256sum $files | base64 -w0)" >> "${GITHUB_OUTPUT}"
          echo "Provenance subjects generated: $files"

  provenance:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      actions: read   # Required to read the workflow path.
      id-token: write  # Required to sign the provenance.
      contents: write  # Required to add assets to a release.
      
    # Use the SLSA generator action to create the provenance file.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: "${{ needs.build.outputs.digests }}"
      upload-assets: true # Optional: Automatically upload to a new release
